<a href="https://colab.research.google.com/github/redom13/ML/blob/main/keras_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import tensorflow as tf
import numpy as np

In [3]:
from tensorflow.keras.layers import Dense,Input

In [4]:
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras import Sequential

In [5]:
from tensorflow.keras.activations import sigmoid

In [7]:
linear_layer=tf.keras.layers.Dense(units=1,activation='linear')

In [8]:
linear_layer.get_weights()

[]

In [12]:
X_train = np.array([[1.0], [2.0]], dtype=np.float32)           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)
print(X_train.shape)     #(price in 1000s of dollars)
# X_train has a single feature. Hence w will have a single wt

(2, 1)


In [13]:
a1=linear_layer(X_train)
print(a1)

tf.Tensor(
[[0.629604]
 [1.259208]], shape=(2, 1), dtype=float32)


In [16]:
w,b=linear_layer.get_weights()
print(f'w:{w},b:{b}')
print(f'w.shape:{w.shape},b.shape:{b.shape}')
# So w is a 2D array

w:[[0.629604]],b:[0.]
w.shape:(1, 1),b.shape:(1,)


In [17]:
set_w=np.array([[200.0]])
set_b=np.array([100.0])
linear_layer.set_weights([set_w,set_b])
a2=linear_layer(X_train)
print(a2)

tf.Tensor(
[[300.]
 [500.]], shape=(2, 1), dtype=float32)


In [22]:
model=Sequential(
    [
        tf.keras.layers.Dense(1,input_dim=1,activation='sigmoid',name='L1')
    ]
)

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 2)                 4         
                                                                 
Total params: 4 (16.00 Byte)
Trainable params: 4 (16.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
logistic_layer=model.get_layer('L1')

In [25]:
w,b=logistic_layer.get_weights()
print(w,b)

[[-0.8009861]] [0.]


In [26]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

In [27]:
set_w = np.array([[2]])
set_b = np.array([-4.5])

In [29]:
logistic_layer.set_weights([set_w,set_b])
print(logistic_layer.get_weights())

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]


In [30]:
a1=model.predict(X_train)
print(a1)

1/1 [==============================] - 0s 183ms/step
[[0.01098694]
 [0.07585818]
 [0.37754068]
 [0.8175745 ]
 [0.97068775]
 [0.99592984]]
