#### 22. Normalize a 5x5 random matrix (★☆☆)

In [1]:
import numpy as np
# Create a 5x5 random matrix
matrix = np.random.random((5, 5))

# Normalize the matrix
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print(normalized_matrix)


[[0.06460916 0.45466779 0.         1.         0.5796326 ]
 [0.09278098 0.07390316 0.94573148 0.27169713 0.75250868]
 [0.50469183 0.77101722 0.51939003 0.32309332 0.51341601]
 [0.7186735  0.84904452 0.02697039 0.0247527  0.70418296]
 [0.47787198 0.61147104 0.19863881 0.36704472 0.56879315]]


This Python code is using the NumPy library to create a 5x5 matrix of random numbers and then normalize it.

1. `import numpy as np`: This line imports the NumPy library and gives it the alias `np`. NumPy is a powerful library for numerical computations in Python.

2. `matrix = np.random.random((5, 5))`: This line creates a 5x5 matrix filled with random numbers. The numbers are drawn from a uniform distribution over [0, 1).

3. `normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))`: This line normalizes the matrix. Normalization is a common operation in machine learning and statistics. It scales all values in a dataset to fall between 0 and 1. The formula for normalization is `(value - min) / (max - min)`. Here, `np.min(matrix)` finds the smallest value in the matrix, and `np.max(matrix)` finds the largest value. The operation is performed element-wise, so each value in the matrix is individually normalized.

4. `print(normalized_matrix)`: This line prints the normalized matrix. After normalization, all values in the matrix will be between 0 and 1, with the smallest original value mapped to 0 and the largest original value mapped to 1.

In [2]:
arr=np.arange(6).reshape(2,3)
print((arr+2)*3)

[[ 6  9 12]
 [15 18 21]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
arr=np.random.randint(1,10,(5,3))
arr2=np.random.randint(5,15,(3,2))
print(arr)
print(arr2)
print(arr@arr2) 
print(np.matmul(arr,arr2))
# these 2 are used for matrix multiplication

[[5 5 2]
 [7 6 5]
 [2 3 8]
 [5 4 2]
 [9 9 3]]
[[ 7  6]
 [ 8 12]
 [11  5]]
[[ 97 100]
 [152 139]
 [126  88]
 [ 89  88]
 [168 177]]
[[ 97 100]
 [152 139]
 [126  88]
 [ 89  88]
 [168 177]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
arr=np.random.randint(1,10,15)
print(arr)
arr=np.where((arr>=3) & (arr<=8),arr*-1,arr) # Checks element-wise
# If satisfied,2nd arg is executed i.e those elements will be negated,else 3rd arg
print(arr)
print(np.where(arr>5)) # Returns the indices of elem satisfying this cond. as an array

[8 4 2 8 1 7 3 3 6 8 3 9 7 3 9]
[-8 -4  2 -8  1 -7 -3 -3 -6 -8 -3  9 -7 -3  9]
(array([11, 14], dtype=int64),)


#### 30. How to find common values between two arrays? (★☆☆)

In [13]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,3,7,9])
print(np.intersect1d(arr1,arr2))

[3 5]


#### 29. How to round away from zero a float array ? (★☆☆)

In [15]:
float_array=[1.2,3,5]
rounded_array = np.ceil(float_array)
print(rounded_array)

[2. 3. 5.]


In [16]:
print(np.sqrt(-1)==np.emath.sqrt(-1))

False


C:\Users\ASUS\AppData\Local\Temp\ipykernel_19760\3643901316.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)==np.emath.sqrt(-1))


This Python code is using the NumPy library to compare the results of two different square root functions: `np.sqrt` and `np.emath.sqrt`.

The expression `np.sqrt(-1)` attempts to calculate the square root of -1 using NumPy's standard square root function. However, the square root of a negative number is not a real number, it's an imaginary number. In the real number domain, this operation is not defined, so `np.sqrt` returns `np.nan` (Not a Number).

On the other hand, `np.emath.sqrt(-1)` calculates the square root of -1 using the `emath` (short for "extended math") module in NumPy, which supports more complex mathematical operations. The `emath.sqrt` function can handle negative inputs by returning an imaginary number. In this case, it returns `1j`, which is the imaginary unit in Python (equivalent to [`i`](command:_github.copilot.openSymbolInFile?%5B%22c%3A%2FUsers%2FASUS%2F.vscode%2Fextensions%2Fms-python.vscode-pylance-2024.4.1%2Fdist%2Ftypeshed-fallback%2Fstdlib%2Fbuiltins.pyi%22%2C%22i%22%5D "c:/Users/ASUS/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/builtins.pyi") in mathematics).

So, the expression `np.sqrt(-1) == np.emath.sqrt(-1)` is comparing `np.nan` to `1j`. Since these two values are not equal, the expression returns `False`.

The [`print`](command:_github.copilot.openSymbolInFile?%5B%22c%3A%2FUsers%2FASUS%2F.vscode%2Fextensions%2Fms-python.vscode-pylance-2024.4.1%2Fdist%2Ftypeshed-fallback%2Fstdlib%2Fbuiltins.pyi%22%2C%22print%22%5D "c:/Users/ASUS/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/builtins.pyi") function then outputs this result, so the code prints `False`.

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [17]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [24]:
today=np.datetime64('today','D')
print(today)
yesterday=np.datetime64('today','D')-np.timedelta64(1,"D") # timedelta is for diff
print(yesterday)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(tomorrow)

2024-04-28
2024-04-27
2024-04-29


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [25]:
print(np.random.randint(0,5,(5,5)))

[[3 1 4 0 4]
 [3 0 1 4 2]
 [2 3 2 3 0]
 [2 3 2 3 1]
 [3 4 4 2 3]]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [27]:
print(np.sort(np.random.randint(1,100,10)))

[21 22 23 30 36 48 58 67 74 83]
