In [2]:
import numpy as np

### Create a null vector

In [6]:
null_vector = np.zeros(10, dtype=int)
print(null_vector)
print(null_vector.size)
# arr=np.array()

[0 0 0 0 0 0 0 0 0 0]
10


### Create a Null vector of size 10 but 5th value is 1

In [8]:
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


### Create a vector with values ranging from `10` to `49`

In [9]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Reverse a Vector `+` Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
reversed_arr = arr[::-1]
print(reversed_arr)
reversed_arr2=np.flip(arr)
print(reversed_arr2)
new_arr=np.arange(8).reshape(2,2,2)
print(new_arr)
print(np.flip(new_arr,0)) # Flip w.r.t axis 0 i.e the 1st axis
# As the size is 2x2x2,1st flipping w.r.t 1st axis means simply flipping the 2 2d arrays
print(np.flip(new_arr,1))
# Now the 2d arrays will be filpped i.e the elements of the 2d arrays will be reversed(which is 1d array)
# But the relative position of the 2D arrays themselves will be the same
print(np.flip(new_arr,2))
# Same logic for this. This time every 1D array will be reversed

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]
[[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]
[[[1 0]
  [3 2]]

 [[5 4]
  [7 6]]]


### Find indices of non-zero elements from `[1,2,0,0,4,0]`

In [34]:
arr=np.array([1,2,0,0,4,0])
print(arr)
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)
zero_indices = np.where(arr == 0) # ==,>,< all allowed,any number(not only 0) allowed
print(zero_indices)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)
(array([2, 3, 5], dtype=int64),)


### 3x3 Identity Matrix

In [37]:
arr=np.eye(3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 3x3x3 matrix with random values

In [40]:
print(np.random.randn(3,3,3)) 
# rand--> Only +ve
# randn--> both +ve & -ve

[[[ 1.36869919  0.11567157  0.12851302]
  [ 0.53167367  1.3209158  -0.27470666]
  [ 1.09489131  1.66042451  1.24973076]]

 [[ 1.81491271  0.89941367 -1.0922314 ]
  [ 0.08462808  0.31858122 -0.50328476]
  [ 0.374599   -0.27757042 -0.1905966 ]]

 [[-1.5610244  -0.2822281  -1.13131615]
  [ 0.95329995 -0.42989859  0.8223401 ]
  [ 0.80062032  2.04966293 -0.10888562]]]


### Create a 10x10 array with random values and find the minimum and maximum values 

In [45]:
randArr=np.random.rand(10,10)
#print(randArr)
print(f"Min: {np.min(randArr)},Max: {np.max(randArr)}")


Min: 0.0014421201495554703,Max: 0.9889899497548167


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
n=4
# arr=np.full((n,n),1)
# print(arr) 
# print(arr-np.zeros_like(n))
# one=np.full((n,),1)
# vertOne=one.reshape((n,1))
# print(one)
# print(vertOne)
# print(arr+vertOne)
# arr=np.full(n,-1)
# arr[0],arr[n-1]=0,0
# print(arr)
# print(vertOne+arr)
arr = np.ones((n, n),dtype=int)
print(arr[1:-1, 1:-1])
arr[1:-1, 1:-1] = 0 # Slicing to select subarray and modify
print(arr)

[[1 1]
 [1 1]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [12]:
arr=np.array([[1,2,3],
              [2,4]])   # Can't create this kind of arrays
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [18]:
arr=np.array([[1,2,3],
              [2,4,6]])
print(np.concatenate((arr,np.arange(2).reshape(2,1)),axis=1))

[[1 2 3 0]
 [2 4 6 1]]


In [19]:
arr=np.array([[1,2,3],
              [2,4,6]])
print(np.concatenate((arr,np.arange(2).reshape(2,1)),axis=0)) # This is not allowed

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [23]:
n=5
arr=np.arange(1,n**2+1,dtype=int).reshape(n,n)
print(arr)
tmp=np.array(arr)
# print(tmp)
tmp[1:-1,1:-1]=0 # Now tmp has zeros at the centre
print(arr-tmp)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 0  0  0  0  0]
 [ 0  7  8  9  0]
 [ 0 12 13 14  0]
 [ 0 17 18 19  0]
 [ 0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [27]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


This Python code is using the NumPy library to demonstrate some peculiarities of floating-point arithmetic and the special values `np.nan` (Not a Number) and `np.inf` (Infinity).

1. `print(0 * np.nan)`: This line multiplies 0 by `np.nan`. According to IEEE floating-point standards, any operation involving `np.nan` results in `np.nan`, so this will print `nan`.

2. `print(np.nan == np.nan)`: This line checks if `np.nan` is equal to itself. Surprisingly, this will print `False`. This is because `np.nan` is not considered equal to any value, including itself.

3. `print(np.inf > np.nan)`: This line checks if `np.inf` is greater than `np.nan`. This will print `False` because comparisons with `np.nan` are always false, even when comparing `np.nan` with itself.

4. `print(np.nan - np.nan)`: This line subtracts `np.nan` from `np.nan`. As mentioned before, any operation involving `np.nan` results in `np.nan`, so this will print `nan`.

5. `print(np.nan in set([np.nan]))`: This line checks if `np.nan` is in a set that contains `np.nan`. This will print `True`. Even though `np.nan` is not equal to itself, it is still the same object, so it can be found in a set.

6. `print(0.3 == 3 * 0.1)`: This line checks if 0.3 is equal to three times 0.1. This might seem straightforward, but it will actually print `False` due to the way floating-point numbers are represented in computers. The value 0.1 cannot be represented exactly as a base 2 fraction, so in binary floating-point, the result of multiplying 0.1 by 3 is not exactly equal to 0.3.

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
n=5
# Naive approach-->
arr=np.zeros((n,n),dtype=int)
for i in range(1, n):
    arr[i,i-1]=i
print(arr)
# Better -->
arr=np.diag(np.arange(1,n),k=-1) # k=1 would have the values over the diagonal
# This function sets the values along diagonal(or maybe below or above) 
# with the values of the vector given as first arg
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
n=8
arr=np.zeros((n,n))
for i in range(0,n,2):
    tmp=np.diag(np.ones(n-i),k=i)
    arr+=tmp
    if i!=0:
        tmp=np.diag(np.ones(n-i),k=i*-1)
        arr+=tmp
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [33]:
n = 8
arr = np.tile([[1, 0], [0, 1]], (n // 2, n // 2))
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [42]:
arr=np.arange(1,12,2).reshape(3,2)
print(arr)
print("After tiling:\n",np.tile(arr,(4,3))) # Shape 4*3x3*2 i.e 12x6
print("Again after tiling\n",np.tile(arr,(2)))
print("Again after tiling\n",np.tile(arr,(1,2)))
# The last 2 are same. As arr is 2d & reps is 1d in the 1st one,it's treated as 1,2
print("Again after tiling\n",np.tile(arr,(3,2,4)))
# Now the o/p is a 3D array,arr was considered as 1x3x2
# So shape of tiled array is 3x6x8

[[ 1  3]
 [ 5  7]
 [ 9 11]]
After tiling:
 [[ 1  3  1  3  1  3]
 [ 5  7  5  7  5  7]
 [ 9 11  9 11  9 11]
 [ 1  3  1  3  1  3]
 [ 5  7  5  7  5  7]
 [ 9 11  9 11  9 11]
 [ 1  3  1  3  1  3]
 [ 5  7  5  7  5  7]
 [ 9 11  9 11  9 11]
 [ 1  3  1  3  1  3]
 [ 5  7  5  7  5  7]
 [ 9 11  9 11  9 11]]
Again after tiling
 [[ 1  3  1  3]
 [ 5  7  5  7]
 [ 9 11  9 11]]
Again after tiling
 [[ 1  3  1  3]
 [ 5  7  5  7]
 [ 9 11  9 11]]
Again after tiling
 [[[ 1  3  1  3  1  3  1  3]
  [ 5  7  5  7  5  7  5  7]
  [ 9 11  9 11  9 11  9 11]
  [ 1  3  1  3  1  3  1  3]
  [ 5  7  5  7  5  7  5  7]
  [ 9 11  9 11  9 11  9 11]]

 [[ 1  3  1  3  1  3  1  3]
  [ 5  7  5  7  5  7  5  7]
  [ 9 11  9 11  9 11  9 11]
  [ 1  3  1  3  1  3  1  3]
  [ 5  7  5  7  5  7  5  7]
  [ 9 11  9 11  9 11  9 11]]

 [[ 1  3  1  3  1  3  1  3]
  [ 5  7  5  7  5  7  5  7]
  [ 9 11  9 11  9 11  9 11]
  [ 1  3  1  3  1  3  1  3]
  [ 5  7  5  7  5  7  5  7]
  [ 9 11  9 11  9 11  9 11]]]


In [44]:
arr=np.arange(1,5)
print(np.tile(arr,(2,3))) # arr as 1x4
print(np.tile(arr,(2,2,2))) # arr as 1x1x4

[[1 2 3 4 1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4 1 2 3 4]]
[[[1 2 3 4 1 2 3 4]
  [1 2 3 4 1 2 3 4]]

 [[1 2 3 4 1 2 3 4]
  [1 2 3 4 1 2 3 4]]]


In [47]:
arr=np.arange(1,6*7*8+1).reshape(6,7,8)
print(arr[1,5,3])

100
