<a href="https://colab.research.google.com/github/redom13/ML/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.3.1+cu121'

In [ ]:
tensor_A=torch.rand(3,2)
tensor_A

tensor([[0.4669, 0.9740],
        [0.8721, 0.4376],
        [0.8868, 0.4836]])

In [ ]:
torch.manual_seed(1)
linear=torch.nn.Linear(in_features=2,out_features=6)
linear


Linear(in_features=2, out_features=6, bias=True)

In [ ]:
x=tensor_A
output=linear(x)
output

tensor([[ 0.1244, -0.0163,  0.0507,  0.2188,  0.0641,  0.1227],
        [ 0.4394, -0.2499, -0.4466, -0.0331,  0.1503,  0.1835],
        [ 0.4304, -0.2366, -0.4368, -0.0187,  0.1478,  0.1880]],
       grad_fn=<AddmmBackward0>)

In [ ]:
linear.weight.shape

torch.Size([6, 2])

In [ ]:
x=torch.arange(1,100,10)
x,x.shape

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.Size([10]))

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked,x_stacked.shape

(tensor([[ 1,  1,  1,  1],
         [11, 11, 11, 11],
         [21, 21, 21, 21],
         [31, 31, 31, 31],
         [41, 41, 41, 41],
         [51, 51, 51, 51],
         [61, 61, 61, 61],
         [71, 71, 71, 71],
         [81, 81, 81, 81],
         [91, 91, 91, 91]]),
 torch.Size([10, 4]))