<a href="https://colab.research.google.com/github/redom13/ML/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.1+cu121'

In [ ]:
tensor_A=torch.rand(3,2)
tensor_A

tensor([[0.4669, 0.9740],
        [0.8721, 0.4376],
        [0.8868, 0.4836]])

In [ ]:
torch.manual_seed(1)
linear=torch.nn.Linear(in_features=2,out_features=6)
linear


Linear(in_features=2, out_features=6, bias=True)

In [ ]:
x=tensor_A
output=linear(x)
output

tensor([[ 0.1244, -0.0163,  0.0507,  0.2188,  0.0641,  0.1227],
        [ 0.4394, -0.2499, -0.4466, -0.0331,  0.1503,  0.1835],
        [ 0.4304, -0.2366, -0.4368, -0.0187,  0.1478,  0.1880]],
       grad_fn=<AddmmBackward0>)

In [ ]:
linear.weight.shape

torch.Size([6, 2])

In [ ]:
x=torch.arange(1,100,10)
x,x.shape

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.Size([10]))

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked,x_stacked.shape

(tensor([[ 1,  1,  1,  1],
         [11, 11, 11, 11],
         [21, 21, 21, 21],
         [31, 31, 31, 31],
         [41, 41, 41, 41],
         [51, 51, 51, 51],
         [61, 61, 61, 61],
         [71, 71, 71, 71],
         [81, 81, 81, 81],
         [91, 91, 91, 91]]),
 torch.Size([10, 4]))

In [2]:
device='cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
torch.cuda.device_count()

1

In [4]:
tensor=torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [5]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [17]:
#torch.cuda.manual_seed(1234)
torch.manual_seed(1234)

In [18]:

rand_tensor_A=torch.rand(3,4)
torch.random.manual_seed(1234)
rand_tensor_B=torch.rand(3,4)
rand_tensor_A,rand_tensor_B

(tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]]),
 tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]]))

In [19]:
tensor_A_on_gpu=rand_tensor_A.to(device)
tensor_B_on_gpu=rand_tensor_B.to(device)
tensor_A_on_gpu,tensor_B_on_gpu

(tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [20]:
print("Are they equal everywhere?")
tensor_A_on_gpu==tensor_B_on_gpu

Are they equal everywhere?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]], device='cuda:0')

In [24]:
new_Tensor=tensor_A_on_gpu.mm(tensor_B_on_gpu.T)
new_Tensor

tensor([[0.3643, 0.4684, 0.5628],
        [0.4684, 0.7161, 0.5757],
        [0.5628, 0.5757, 1.4951]], device='cuda:0')

In [26]:
new_Tensor.max(),new_Tensor.min()

(tensor(1.4951, device='cuda:0'), tensor(0.3643, device='cuda:0'))

In [25]:
new_Tensor.argmin()

tensor(0, device='cuda:0')

In [27]:
SEED=7
torch.manual_seed(SEED)
x=torch.rand(1,1,1,10)
x,x.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [29]:
x_squeezed=x.squeeze()
x_squeezed,x_squeezed.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))